# Generated by Django 6.0.7 on 2026-08-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_file', models.FileField(upload_to='videos/originals/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('source_height', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'video_assets',
            },
        ),
        migrations.CreateModel(
            name='VideoRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=10)),
                ('file', models.FileField(upload_to='videos/renditions/')),
                ('bitrate_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('video_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='media_processing.videoasset')),
            ],
            options={
                'db_table': 'video_renditions',
                'unique_together': {('video_asset', 'resolution')},
            },
        ),
    ]
