name: dev_edu
services:
  redis:
    image: redis:7
    container_name: dev_edu_redis
    volumes:
      - redisdata:/data

  web:
    build: .
    container_name: dev_edu_web
    volumes:
      - .:/app
    ports:
      - "8000:8000" # host:container
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    container_name: dev_edu_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery_worker_default:
    container_name: dev_edu_worker_default
    build: .
    command: celery -A config worker -Q default -l info --concurrency=1
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on: [db, redis]

  celery_worker_media:
    container_name: dev_edu_worker_media
    build: .
    command: celery -A config worker -Q media -l info --concurrency=1
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    volumes:
      - media_volume:/app/media
    depends_on: [db, redis]

volumes:
  postgres_data:
  redisdata:
  media_volume:
