# Generated by Django 6.0.7 on 2026-08-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted_for_review', 'Submitted for review'), ('published', 'Published'), ('deleted', 'Deleted'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
